galaxy.yml
Fixes:
- Removes duplicate `license` key because `license_file` serves the same purpose
- Updates documentation link
- Excludes test files from build artifact
=> Address linting issues with the galaxy manifest.

Makefile
Resolves issue where running the test commands from the Makefile (`test/unit` & `test/integration`) would return an error about an invalid path.
The filename for the test runner changed from `run_tests.sh` to `run-tests.sh`, but the change was not reflected in the Makefile.
=> Fix the path to the collection test script in the Makefile 

README.md, plugins/module_utils/const.py, plugins/modules/generic_item.py
Resolves #16 
Change will allow users to specify `category: api_credential` when defining a vault item in a playbook. This ensures we remain aligned with the other 1Password Connect SDKs and connectors.
=> Add support for API_CREDENTIAL item type.

README.md
With the changes made in #15, we needed to update the README to reflect the new values.
This PR:
- Explains differences between `state: present` / `state: absent`
- Updates example codeblocks
- Explains what the 3 values for `generate_value` mean
- Removes old explanations for deprecated state values
- Adds link to 1Password Secrets Automation homepage.
=> Update documentation with new `state` and `generate_value` settings.

plugins/module_utils/const.py, plugins/modules/generic_item.py
Harmonizes Ansible collection with other integrations that support all item types. Using an item type is not required, but we should still have a consistent experience across all Connect integrations.
Fixes #22
=> Add more supported item type choices

plugins/module_utils/const.py, plugins/module_utils/specs.py, plugins/modules/generic_item.py
_This PR is another pre-requisite for #20_ 
Switches the default item type to `API_CREDENTIAL`, which has no required fields and offers the most flexibility when creating an item with custom fields.
Using`LOGIN` or `PASSWORD` as the item type default value introduced hidden field requirements around "username" and "password" fields. The `API_CREDENTIAL` type is more or less equivalent to an empty item.
~~**This may impact users if the items in their playbooks do not have a category value**. In practice, a login field may turn into an api_credentials field if a customer updates to the latest collection version and does not explicitly define the item type as `login`.~~ 
Edit: **Item categories cannot be changed after creating an item.** Items created after updating to the collection version …
=> WIP: Change item type default to `API_CREDENTIAL`

plugins/module_utils/fields.py, plugins/modules/item_info.py
Previously, Ansible copied the item's `notesField` only if `notesField` occurred in the playbook parameters as a field definition. This meant the `notesField` may be removed when updating an existing item.We actually want to preserve the `notesField` whether or not the user is trying to overwrite it. 
This MR yields the existing `notesField`, if it exists, before looping through the playbook params. As before, the `notesField` is ignored if it is defined in the playbook params.
**UTF-8 Normalization**
This MR also adds additional label normalization when calling `_get_field_by_label()`. Now we take the extra step to ensure utf8 characters are normalized before comparing the two strings.
=> Preserve notesField regardless of playbook params & use utf8 normalization for labels

plugins/module_utils/const.py, plugins/module_utils/errors.py, plugins/module_utils/fields.py, plugins/module_utils/specs.py, plugins/module_utils/vault.py, plugins/modules/generic_item.py, plugins/modules/item_info.py, tests/integration/targets/generic_item/tasks/tests.yml, tests/unit/plugins/module_utils/test_item_assembly.py, tests/unit/plugins/module_utils/test_item_crud.py
👉 Merge after #27 
🔨  Fixes #20 
This PR updates how Ansible assigns a field's `purpose` when creating a `PASSWORD` or `LOGIN` item. The `purpose` assignments help the Connect server set "Primary Password" and "Primary Username" for item types that have "primary" field support.
The **Password** item type requires one concealed field with the `PASSWORD` purpose. 
Previously, we did not check for whether a Password item had a concealed field before sending it to the Connect server. If that was the case, users would receive vague validation errors from Connect server.
Instead, the Ansible `generic_item` module now asserts there is 1 concealed field named `password` when the item type 
is `PASSWORD`. [1]
In addition to a required `PASSWORD` purpose field, the **Login** item has an optional …
=> Fix field_purpose assignment when item type is PASSWORD or LOGIN.

plugins/module_utils/api.py, plugins/modules/item_info.py, tests/integration/targets/generic_item/tasks/tests.yml
Fixes an issue where calling `api.get_item_by_name` returned item overview data instead of the full item definition. This meant when a user only provided the item name the playbook would think the item didn't have existing values. 
In certain cases, this led to values defined as `generate: on_create` to be regenerated every time.
Looking up an item by name only returned the overview data for an item. There was a mistaken assumption that filtering by item name would return the item's full structure. We added a test to make sure the updated item does not make any unexpected field changes when defining an item in a playbook by name.
=> The `get_item_by_name` client method should return the full item response

Makefile, plugins/module_utils/api.py, plugins/module_utils/errors.py, plugins/module_utils/fields.py, plugins/module_utils/vault.py, scripts/run-tests.sh, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt, tests/unit/plugins/module_utils/test_item_crud.py
The RedHat Automation Hub has more requirements around compatibility than Ansible Galaxy. We needed to improve compatibility with Python versions prior to 3.6 because of customer expectations for runtime support.
We can revisit the compatibility changes once minimum versions are bumped up.
- Use ansible's [built-in](https://docs.ansible.com/ansible/latest/dev_guide/developing_python_3.html#import-ansible-s-bundled-python-six-library) `six` library when working with `urllib`
- Use "old style" `super()` calls
- Remove f-strings, replace with [py2.6-compatible](https://docs.ansible.com/ansible/latest/dev_guide/developing_python_3.html#use-str-format-for-python-2-6-compatibility) `.format()`
- str / bytes compatibility
- Introduce exclusions for sanity test false-positives in the …
=> Improve Python2 and Python3.5 compatibility

README.md
* Adds section about the `field_info` module to the README
* Fixes syntax for Markdown table
* Adds ansible-core compatibility statement, as required by Ansible Automation Hub.
=> Update README with field_info example, Ansible compatibility statement

plugins/module_utils/const.py, plugins/modules/generic_item.py
Resolves #46 
This PR resolves an issue when trying to create an item with an OTP field. The server expects "OTP", not "TOTP" as a field type. 
I've changed the internal enum value to point to `OTP` and updated the relevant module documentation. This shouldn't be a breaking change because it's fixing an existing issue 😄
=> Fix OTP field type label and value.

tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
Adds the new `field_info` module to the list of files excluded from the `validate-modules:missing-gplv3-license` test.
This change follows the `ansible-test` [Ignore File Format](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/ignores.html#ignore-file-format).
We don't include the GPLv2 header in our files because we opted to use the MIT license for our collection instead.
=> Exclude GPL License check during ansible sanity tests

galaxy.yml
Adding an Ansible Automation Hub tag ('security') to add compliance with the Automation Hub guidelines.
Available AH tags to use: 
* application
* cloud
* database
* infrastructure
* linux
* monitoring
* networking
* security
* storage
* tools
* windows
=> Add AH tag

.github/workflows/ansible-sanity.yml, .github/workflows/ansible-tests.yml, plugins/modules/field_info.py, tests/unit/plugins/module_utils/test_item_assembly.py
Adds automated `ansible-test sanity` and `ansible-test units` GitHub workflows. The `ansible-test sanity` job is run for each version of `ansible-core` supported by the collection. 
"Sanity" tests are equivalent to lint tests, and do not require a Connect server to run.
**Supported `ansible-core` versions**:
- 2.9 (⚠️ deprecated beginning **December 2022**)
- 2.10
- 2.11
- 2.12 
The GitHub action will run a sanity test suite for each ansible version listed above.
This workflow was heavily inspired by [T-Systems-MMS/ansible-collection-icinga-directory](https://github.com/T-Systems-MMS/ansible-collection-icinga-director/blob/35ce15a5529d9a3f23dcfb671c02147747475813/.github/workflows/main.yml).
=> Add GitHub action for Ansible sanity tests

plugins/module_utils/api.py
Fix for the issue #58 
It fails with `400 Bad request` error when using `item_info` plugin to retrieve `item` by title.
**Current implementation:**
When getting an error from the rest-api it tries to parse the body and fails.
**Fix:**
Parse only success responses and process the error ones.
=> properly process http errors

meta/runtime.yml
Ansible Galaxy silently began requiring a meta/runtime.yml file when uploading a collection. This requirement came into effect around July 2021
See also:
[1] https://issues.redhat.com/browse/AAH-538
[2] https://github.com/ansible/galaxy-importer/pull/122
=> Add required meta/runtime.yml for Ansible Galaxy compat

plugins/module_utils/api.py
Description:
Bad request 400 returns when fetch existing item by title. [Detailed description.](https://1password.community/discussion/123474/connect-server-api-shows-unable-to-find-existing-span-for-request-then-400-bad-request-in-logs)
Solution:
Distinguish success responses by status code.
=> improved handling errors

README.md
Using `OP_VAULT` environment variable doesn't work
=> Fixed typo `OP_VAULT` -> `OP_VAULT_ID` in README.md

.github/workflows/ansible-tests.yml, .github/workflows/release-pr.yml, CONTRIBUTE.md, LICENSE.md, USAGEGUIDE.md, meta/runtime.yml, plugins/module_utils/api.py, plugins/modules/field_info.py, plugins/modules/generic_item.py, plugins/modules/item_info.py, scripts/prepare-release.sh, scripts/run-tests.sh, tests/unit/plugins/module_utils/test_item_assembly.py, tests/unit/plugins/module_utils/test_item_crud.py
This PR updates the piplines to use minimum ansible-core version `2.13` as older versions have EOL(end of life) status. See [support-matrix](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix).
Versions of `ansible-core` and `ansible` in USAGEGUIDE.md and CONTRIBUTE.md was changed according to the [ansible community changelog](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-community-changelogs). But collection is still working on the `ansible-core` versions `<2.13`.
Tested the collection locally using `ansible-core 2.13.x, 2.14.x, 2.15.x` by running simple playbook `ansible-playbook 1pass_playbook.yml` and verified that it works with Connect server.
=> Update ci scripts

.ansible-lint, .github/workflows/ansible-lint.yml, .github/workflows/ansible-tests.yml, CONTRIBUTE.md, Makefile, README.md, changelogs/config.yaml, galaxy.yml, meta/runtime.yml, plugins/modules/generic_item.py, tests/integration/targets/field_info/tasks/main.yml, tests/integration/targets/field_info/tasks/tests.yml, tests/integration/targets/generic_item/tasks/main.yml, tests/integration/targets/generic_item/tasks/tests.yml, tests/integration/targets/generic_item/vars/main.yml, tests/integration/targets/item_info/tasks/main.yml, tests/integration/targets/item_info/tasks/tests.yml
This PR makes the changes required to make as `ansible-core v2.13` is end of life.
Changes are done:
- `ansible-core v2.14` is used in the following files `CHANGELOG.md`, `README.md`, `meta/runtime.yml`
- `ansible-lint` GitHub Actions workflow is added to lint the collection.
-  `.github/workflows/ansible-tests.yml` exclude `v2.13` and include `v2.16`. Also slightly update the test matrix to run each sanity check on the compatible python version from `python` matrix array.
- The rest of the files are changed due to fixing `lint` errors and warnings.
The new version will be released after this PR is merged.
=> Bump ansible-core v2.14

.ansible-lint, .github/workflows/ansible-lint.yml, .github/workflows/ansible-tests.yml, CONTRIBUTE.md, README.md, changelogs/changelog.yaml, changelogs/config.yaml, meta/runtime.yml, tests/config.yml
This PR makes the following changes:
- Set Ansible Core `2.15` as the minimum required version
- Set Python `3.9` as the minimum required Python version.
- Upgrade `ansible-lint` to `6.22.2` and adjust code based on new lint rules.
- Remove Ansible Core 2.14 from the codebase and pipeline testing matrix.
- Add Python `3.12` as a supported version since it's supported with Ansible Core `2.16`.
Closes #89.
=> Remove Ansible core 2.14 and set 2.15 as minimum required version

plugins/module_utils/api.py
As per the 1Password Connect Server API reference, the expected status code for DELETE operation is 204. api.py would always expect a 200 status code, so a successful DELETE operation incorrectly registered as a failure. This commit adds 204 as a success status code. Ref: https://developer.1password.com/docs/connect/connect-api-reference/#delete-an-item
=> Add 204 as a valid status code for DELETE operation in api.py
